"""
Diet Module - Modular Diet Generation System
=============================================
Refactored from monolithic diet_service.py for better maintainability
"""

from .constants import (
    # Limits
    TOL_PERCENT,
    MIN_FOOD_GRAMS,
    MAX_FOOD_GRAMS,
    MAX_CARB_GRAMS,
    MIN_MEAL_CALORIES,
    MIN_DAILY_CALORIES,
    MAX_COTTAGE_TOTAL,
    MAX_AVEIA_TOTAL,
    MAX_IOGURTE_OCORRENCIAS,
    MIN_PROTEINS,
    MIN_CARBS,
    MIN_FATS,
    MIN_FRUITS,
    
    # Defaults
    DEFAULT_PROTEINS,
    DEFAULT_CARBS,
    DEFAULT_FATS,
    DEFAULT_FRUITS,
    
    # Food sets
    ALIMENTOS_PERMITIDOS_LANCHE,
    RESTRICTION_EXCLUSIONS,
    PROTEINS_PRINCIPAIS,
    PROTEINS_LEVES,
    CARBS_PRINCIPAIS,
    CARBS_COMPLEMENTARES,
    CARBS_LANCHE,
    CARBS_ALMOCO_JANTAR,
    GORDURAS_PRINCIPAIS,
    GORDURAS_SNACKS,
    FRUTAS_FREQUENTES,
    FRUTAS_OPCIONAIS,
    LEGUMES_PRINCIPAIS,
    VERDURAS_SALADA,
    PROTEINS_ALMOCO_JANTAR,
    CARNES_APENAS_ALMOCO_JANTAR,
    FOODS_CAFE_LANCHE_MANHA,
    FOODS_LANCHE_TARDE,
    
    # Meal types
    MEAL_TYPE_CAFE,
    MEAL_TYPE_LANCHE_MANHA,
    MEAL_TYPE_ALMOCO,
    MEAL_TYPE_LANCHE_TARDE,
    MEAL_TYPE_JANTAR,
    MEAL_TYPE_CEIA,
    
    # Data
    FOODS,
    SUPPLEMENTS,
)

__all__ = [
    # Limits
    'TOL_PERCENT',
    'MIN_FOOD_GRAMS',
    'MAX_FOOD_GRAMS',
    'MAX_CARB_GRAMS',
    'MIN_MEAL_CALORIES',
    'MIN_DAILY_CALORIES',
    'MAX_COTTAGE_TOTAL',
    'MAX_AVEIA_TOTAL',
    'MAX_IOGURTE_OCORRENCIAS',
    'MIN_PROTEINS',
    'MIN_CARBS',
    'MIN_FATS',
    'MIN_FRUITS',
    
    # Defaults
    'DEFAULT_PROTEINS',
    'DEFAULT_CARBS',
    'DEFAULT_FATS',
    'DEFAULT_FRUITS',
    
    # Food sets
    'ALIMENTOS_PERMITIDOS_LANCHE',
    'RESTRICTION_EXCLUSIONS',
    'PROTEINS_PRINCIPAIS',
    'PROTEINS_LEVES',
    'CARBS_PRINCIPAIS',
    'CARBS_COMPLEMENTARES',
    'CARBS_LANCHE',
    'CARBS_ALMOCO_JANTAR',
    'GORDURAS_PRINCIPAIS',
    'GORDURAS_SNACKS',
    'FRUTAS_FREQUENTES',
    'FRUTAS_OPCIONAIS',
    'LEGUMES_PRINCIPAIS',
    'VERDURAS_SALADA',
    'PROTEINS_ALMOCO_JANTAR',
    'CARNES_APENAS_ALMOCO_JANTAR',
    'FOODS_CAFE_LANCHE_MANHA',
    'FOODS_LANCHE_TARDE',
    
    # Meal types
    'MEAL_TYPE_CAFE',
    'MEAL_TYPE_LANCHE_MANHA',
    'MEAL_TYPE_ALMOCO',
    'MEAL_TYPE_LANCHE_TARDE',
    'MEAL_TYPE_JANTAR',
    'MEAL_TYPE_CEIA',
    
    # Data
    'FOODS',
    'SUPPLEMENTS',
]
